sudo: required
services:
    - docker


before_install:
  - docker build -t kjones8812/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_sucess:
  - docker build -t kjones8812/multi-client ./client
  - docker build -t kjones8812/multi-nginx ./nginx
  - docker build -t kjones8812/multi-server ./server
  - docker build -t kjones8812/multi-worker ./worker
#Log into docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to hub
- docker push kjones8812/multi-client
- docker push kjones8812/multi-nginx
- docker push kjones8812/multi-server
- docker push kjones8812/multi-worker
